variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

before_script:
  - docker info

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:stable-dind
  script:
    - |
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
