FROM golang AS builder
ENV GO111MODULE=on
ENV CGO_ENABLED=0
WORKDIR $GOPATH/src
COPY {{outputFolder}} .
WORKDIR $GOPATH/src/{{sourceFolder}}
RUN go mod download

RUN go test ./...

RUN GIN_MODE=release go build -a -o /goserver main.go

FROM SCRATCH AS runtime

COPY --from=builder /goserver /bin
EXPOSE {{serverPort}}/tcp
ENTRYPOINT ["/bin/goserver"]